# Generated by Django 3.2.4 on 2021-07-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium_member',
            field=models.BooleanField(default=False, verbose_name='premium member'),
        ),
    ]
