# Generated by Django 3.2.4 on 2021-07-06 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('model_number', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('specification', models.TextField()),
                ('product_size', models.CharField(blank=True, max_length=50, null=True)),
                ('min_order_quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(max_length=100)),
                ('price_1', models.CharField(max_length=100)),
                ('min_quantity_1', models.CharField(max_length=100)),
                ('max_quantity_1', models.CharField(max_length=100)),
                ('price_2', models.CharField(blank=True, max_length=100, null=True)),
                ('min_quantity_2', models.CharField(blank=True, max_length=100, null=True)),
                ('max_quantity_2', models.CharField(blank=True, max_length=100, null=True)),
                ('price_3', models.CharField(blank=True, max_length=100, null=True)),
                ('min_quantity_3', models.CharField(blank=True, max_length=100, null=True)),
                ('max_quantity_3', models.CharField(blank=True, max_length=100, null=True)),
                ('price_4', models.CharField(blank=True, max_length=100, null=True)),
                ('min_quantity_4', models.CharField(blank=True, max_length=100, null=True)),
                ('max_quantity_4', models.CharField(blank=True, max_length=100, null=True)),
                ('price_5', models.CharField(blank=True, max_length=100, null=True)),
                ('min_quantity_5', models.CharField(blank=True, max_length=100, null=True)),
                ('max_quantity_5', models.CharField(blank=True, max_length=100, null=True)),
                ('in_stock', models.BooleanField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
