# Generated by Django 3.2.4 on 2021-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210709_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(max_length=100),
        ),
    ]
