# Generated by Django 3.2.4 on 2021-07-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_quantity_1',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='min_quantity_1',
            new_name='min_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_1',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_quantity_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_quantity_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_quantity_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_quantity_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_quantity_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_quantity_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_quantity_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_quantity_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_5',
        ),
    ]
